# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fio_api"
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Robin Bortlik"]
  s.date = "2013-07-15"
  s.description = "API wrapper for FIO bank"
  s.email = "robinbortlik@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "fio_api.gemspec",
    "lib/base.rb",
    "lib/base/account.rb",
    "lib/base/deserializer.rb",
    "lib/base/deserializers/list_response_deserializer.rb",
    "lib/base/list.rb",
    "lib/base/request.rb",
    "lib/base/transaction.rb",
    "lib/fio_api.rb",
    "lib/utils/hash.rb",
    "spec/base/account_spec.rb",
    "spec/base/deserializer_spec.rb",
    "spec/base/deserializers/list_response_deserializer_spec.rb",
    "spec/base/list_spec.rb",
    "spec/base/request_spec.rb",
    "spec/base/transaction_spec.rb",
    "spec/fio_api_spec.rb",
    "spec/spec_helper.rb",
    "spec/utils/hash_spec.rb"
  ]
  s.homepage = "http://github.com/robinbortlik/fio_api"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "API wrapper for FIO bank"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.9.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rspec-mocks>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.2.0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
    else
      s.add_dependency(%q<httparty>, [">= 0.9.0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rspec-mocks>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.2.0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.4"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.9.0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rspec-mocks>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.2.0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.4"])
  end
end

